### ISSUE TITLE
Centos Stream update conflict

### ISSUE THREAD

**Issue by LecrisUT** [openhpc/ohpc#1277]
There seems to be an update conflict on `hwloc-libs`. Is version `1.11.9` strictly necessary or can it be update to use `base-os` newer versions?
```
# dnf update
- cannot install both hwloc-libs-2.2.0-1.el8.x86_64 and hwloc-libs-1.11.9-3.el8.x86_64
```

**Comment by adrianreber** [comment]
Would have been good to see which package creates this conflict. But I guess this is one of the differences when running with CentOS stream.

Using CentOS 8.2 I see hwloc-libs-1.11.9-3 CentOS stream has hwloc-libs-2.2.0-1. Looking at the provides of both packages:
```
$ rpm -qp hwloc-libs-2.2.0-1.el8.x86_64.rpm --provides
hwloc-libs = 2.2.0-1.el8
hwloc-libs(x86-64) = 2.2.0-1.el8
libhwloc.so.15()(64bit)
$ rpm -qp hwloc-libs-1.11.9-3.el8.x86_64.rpm --provides
hwloc-libs = 1.11.9-3.el8
hwloc-libs(x86-64) = 1.11.9-3.el8
libhwloc.so.5()(64bit)
```
I see different SO names and so everything linking against hwloc needs to be rebuild. This will happen with the next release and I am pretty sure it is just a simple rebuild, but as OpenHPC 2.0 targets 8.2 we will not rebuild against a package in stream or the upcoming 8.3 release. This will probably be fixed in OpenHPC 2.1.

@koomie any further comments from your side?

**Comment by jcsiadal** [comment]
A user just encountered this issue. Is there any reason not to link Slurm to hwloc-ohpc in devtools?

**Comment by adrianreber** [comment]
I think the general idea is to not replace OS provided packages if they are new enough. There was no reason to maintain a version of hwloc for ourselves any more. hwloc has not been built by OpenHPC for the 2.x branch until now.

Both reports, this one and the one on the mailing list, were caused by usage of CentOS Stream which should not be used.

My main question is why are people using CentOS Stream. Is that documented somewhere? As CentOS Stream is a moving target there will always be the possibility that something breaks and we cannot start to include all the packages which are breaking because of CentOS Stream.

**Comment by LecrisUT** [comment]
As a user, I prefer CentOS Stream for the ease of upgrade, i.e. no more nightmares upgrading from 6 to 7 to 8, etc. and finding what has been deprecated along the way. CentOS Stream should only be one minor update ahead of the main non-Stream version, but still not as advanced or the equivalent RedHat or Fedora. It does create difficulties for updates, but those updates will eventually be part of the main version, so it only serves as early reminders for developers to update their current package for future support.

A solution to this would be to create an equivalent `OpenHPC stream` release, where preliminary patches can be posted and prepare for the next major releases of the main OS.

One upside to the `CentOS Stream` is that it can be turned on/off, upgraded/downgraded to the main version on the same machine with the same configuration, and you would easily see which package is creating incompatibilities without having to run multiple OS.

EDIT: [Relevant article to CentOS Stream](https://wiki.centos.org/Manuals/ReleaseNotes/CentOSStream#Presenting_CentOS_Stream)

**Comment by adrianreber** [comment]
Thanks for the explanation and the link. Reading the link I see that CentOS stream is a development release and not described as a production release. It is helpful for developers, like OpenHPC, to be prepared for the next release of CentOS and RHEL. Like in this case, we can make sure OpenHPC is ready to work, once CentOS 8.3 is released. From my understanding CentOS Stream was never positioned as a production environment.

I understand that it makes upgrading easier, but from my point of view not something OpenHPC can support.

**Comment by LecrisUT** [comment]
Yes, actively supporting it as production environment is not something anyone who installs CentOS Stream would expect. It is enough if we can provide with early heads up on the changes of upcoming releases, so that packages can be updated in preparation of new releases. Since CentOS stream is just behind the RHEL Stream, all the package updates are likely locked in place, so there wouldn't be any concern that some package updates will not be eventually implemented, all of that is already handled in RHEL Stream.

In such sense it would make sense to make a CI/CD, Github Action, etc. to keep track of the CentOS stream updates so that such incompatibilities can be automatically picked up.

**Comment by adrianreber** [comment]
> Since CentOS stream is just behind the RHEL Stream, all the package updates are likely locked in place, so there wouldn't be any concern that some package updates will not be eventually implemented, all of that is already handled in RHEL Stream.

I don't think this is true. It is very unlikely.

> In such sense it would make sense to make a CI/CD, Github Action, etc. to keep track of the CentOS stream updates so that such incompatibilities can be automatically picked up.

That sounds like a good idea. GitHub Actions and Travis both provide a way to have scheduled, cron like runs. With the switch to travis-ci.com I used all my free Travis credits within just one day on my personal account, so GitHub Actions sounds like a good idea. Have a daily run to install all packages against CentOS Stream could be used to easily uncover problems like this.

**Comment by truatpasteurdotfr** [comment]
CentOS Stream is the future of what will be the next RHEL minor/major release.
https://wiki.centos.org/FAQ/CentOSStream

**Comment by viniciusferrao** [comment]
Hi @adrianreber I'm the one on the mailing list that used CentOS Stream.

I'm heavily against it, because it break things. I don't like it, but it is on the official documentation of OpenHPC that stream should be used: https://github.com/openhpc/ohpc/blob/1e970dd16d10b2c252b5f385a49b45fdd678311e/docs/recipes/install/centos8/x86_64/xcat/slurm/steps.tex#L112

I was installing the system on "automatic" and haven't realized this. If I was more focused I would have ignored the line and questioned about it on the mailing list.

**Comment by LecrisUT** [comment]
Heads up regarding the future of centos. According to their [post](https://blog.centos.org/2020/12/future-is-centos-stream/) they'll be switching completely to stream in 2021.

**Comment by frans42** [comment]
We are experimenting with Centos 8 Stream as an OS. Understandably, this might not be a release that OHPC developers want to build a binary repo against. Therefore my question:

Would it be possible to add recipes for install from source (deb & rpm)?

On open source/linux systems the generic fall back is usually an installation from source. I guess for OHPC a possibility would be to provide information/a script for how to build a local repository from source before continuing with a recipe for a binary install from this local repo. This should allow for both, freedom of users to pick their favorite distribution while allowing the developers to restrict to a small number of distros to test against and provide updates for.

We are planning to build more from source again and given the time required to build our application stack, building OHPC on top of this seems perfectly acceptable.

**Comment by adrianreber** [comment]
> We are experimenting with Centos 8 Stream as an OS. Understandably, this might not be a release that OHPC developers want to build a binary repo against. Therefore my question:
> 
> Would it be possible to add recipes for install from source (deb & rpm)?

Are you more interested in using CentOS Stream or building from source. If you are successfully using OpenHPC with CentOS Stream we would love to hear it. At this point I would expect it just works. Do you see any problems?

Concerning building from source: There are a couple of scripts in the misc folder which I was using some months ago to figure out the correct order in which packages have to be built and a script which will create an SRPM for you, which can then be used to build the binary RPM.

**Comment by frans42** [comment]
> > We are experimenting with Centos 8 Stream as an OS. Understandably, this might not be a release that OHPC developers want to build a binary repo against. Therefore my question:
> > Would it be possible to add recipes for install from source (deb & rpm)?
> 
> Are you more interested in using CentOS Stream or building from source. If you are successfully using OpenHPC with CentOS Stream we would love to hear it. At this point I would expect it just works. Do you see any problems?
> 
> Concerning building from source: There are a couple of scripts in the misc folder which I was using some months ago to figure out the correct order in which packages have to be built and a script which will create an SRPM for you, which can then be used to build the binary RPM.

I'm interested in using stream, in particular, since it is now ahead of RHEL. I believe a future consequence of this is the need for an install from source:

Currently, it just works. However, in the future there might be more frequent blips like the hwloc one. Even though, in my opinion, that was a red-hat problem (I don't see why it was not possible to have both hwloc library versions present for a transition period), it would be necessary to respond quickly. This could be via weekly builds of binary repos, but I think building from source is an easier option also for pinning against a specific date (maintaining versions locally).

It will require more attention on the cluster admin side. For example, when building the image, the installation of a grub2 package (grub2-tools) was missing in the recipe. A larger package was probably split up recently by red-hat/centos. No big deal if done in preparation of a cluster install, but would put extra workload on integration testing if devs wanted to support this. They would need to check things like this for every build while I would only need to do this once for the first image.

Conclusion: I would be happy with indirect support via install from source.

**Comment by adrianreber** [comment]
> Conclusion: I would be happy with indirect support via install from source.

I personally think that following CentOS Stream does not require building from source (99% of the time at least), but if you want to build from source you can either take the SRPMs from https://obs.openhpc.community/ and use our build order script to figure out the correct order to rebuild the packages or you can use the scripts from git to build the SRPMS yourself.

If you are using one of these options we can link to your documentation for other interested users if you want to.
